---
services:
  gateway:
    image: ${REGISTRY}/gateway:latest
    build:
      context: .
      dockerfile: Dockerfile.gateway
    ports:
      - "80:3000"
    depends_on:
      - auth-service
      - vitals-service
      - patient-service
    networks:
      - coursework-net
    restart: unless-stopped

  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    environment:
      - MONGO_URI=mongodb://mongodb:27017/authdb
    networks:
      - coursework-net
    restart: unless-stopped

  vitals-service:
    build:
      context: .
      dockerfile: services/diagnostics-vitals-service/Dockerfile
    networks:
      - coursework-net
    restart: unless-stopped

  patient-service:
    build:
      context: .
      dockerfile: services/patient-registration-service/Dockerfile
    networks:
      - coursework-net
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - coursework-net

networks:
  coursework-net:
    driver: bridge
