apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: coursework
  labels:
    app: gateway
    app.kubernetes.io/part-of: coursework
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
        app.kubernetes.io/part-of: coursework
    spec:
      imagePullSecrets:
        - name: acr-registry
      containers:
        - name: gateway
          image: hwudevopsregistry-e9a8dkdbanfebbhh.azurecr.io/gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: coursework-config
                  key: NODE_ENV
            - name: GATEWAY_PORT
              valueFrom:
                configMapKeyRef:
                  name: coursework-config
                  key: GATEWAY_PORT
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: coursework-config
                  key: AUTH_SERVICE_URL
            - name: PATIENT_REG_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: coursework-config
                  key: PATIENT_REG_SERVICE_URL
            - name: DIAGNOSTICS_VITALS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: coursework-config
                  key: DIAGNOSTICS_VITALS_SERVICE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: coursework-app-secrets
                  key: JWT_SECRET
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
