apiVersion: v1
kind: Service
metadata:
  name: vitals-service
  namespace: coursework
  labels:
    app: vitals-service
    app.kubernetes.io/part-of: coursework
spec:
  type: ClusterIP
  selector:
    app: vitals-service
  ports:
    - name: http
      port: 3004
      targetPort: 3004
